[project]
name = "EV_Recommender"
version = "0.1.0"
description = "Recommend an electric vehicle"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.0",
]
